source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Airline' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Airline
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'

end
